<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LTPBAN292363013" failures="3" tests="3" name="Test(failed)" time="56.71" errors="0" timestamp="2025-03-03T18:09:27 IST">
  <testcase classname="testCases.TC3_LoginTestDDT" name="VerifyLogin" time="11.356">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testCases.TC3_LoginTestDDT.VerifyLogin(TC3_LoginTestDDT.java:40)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- VerifyLogin -->
  <testcase classname="testCases.TC3_LoginTestDDT" name="VerifyLogin" time="21.863">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at testCases.TC3_LoginTestDDT.VerifyLogin(TC3_LoginTestDDT.java:53)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- VerifyLogin -->
  <testcase classname="testCases.TC3_LoginTestDDT" name="VerifyLogin" time="11.927">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testCases.TC3_LoginTestDDT.VerifyLogin(TC3_LoginTestDDT.java:40)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- VerifyLogin -->
</testsuite> <!-- Test(failed) -->
